/**
 * 
 */
package com.jhu.openbaltimore.model;
import javax.persistence.*;

/**
 * The class Restaurant models a restaurant that can be viewed by the public. It is a JPA Entity with table "restaurant". The primary key
 * (Long id) is automatically generated by the database. 
 * 
 * @author Zach Earl
 *
 */
@Entity
@Table(name = "restaurant")
public class Restaurant {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Column(length = 50)
	private String name;
	@Column(length = 5)
	private String zipCode;
	@Column(length = 50)
	private String neighborhood; 
	@Column(length = 50)
	private String address;
	
	public Restaurant() {
		super();
	}
	
	public Restaurant(Long id, String name, String zipCode, String neighborhood, String address) {
		super();
		this.id = id;
		this.name = name;
		this.zipCode = zipCode;
		this.neighborhood = neighborhood;
		this.address = address;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getNeighborhood() {
		return neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	
	

}
